# Generated by Django 6.1.1 on 2026-09-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='marketing_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_contact_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
